# Generated by Django 5.0 on 2026-02-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_item_item_alter_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='order',
        ),
    ]
